server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: paymentdb
  sslmode: disable
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchange: payment_exchange
  queue: payment_processing
  durable: true
  
request:
  timeout: 30s